/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download this OpenAPI specification
         * @description Serves this `openapi.yaml` document from the running backend, so
         *     clients and tooling can generate typed bindings without a copy of the
         *     repository.
         */
        get: operations["getOpenApiSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check GraphDB connectivity
         * @description Verifies that the configured GraphDB repository answers a trivial `ASK` query.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_class_hierarchy_metadata/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all ontology classes with their direct parents
         * @description Returns every project-local OWL class together with the list of its
         *     direct named superclasses. The frontend builds the class tree from the
         *     parent arrays (classes with an empty `parents` array are roots).
         */
        get: operations["getClassHierarchyMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search classes and instances by name or label
         * @description Case-insensitive substring search over the local names and labels of
         *     project classes and instances. Each result group is capped at `limit`;
         *     matches on a name prefix rank before other matches. Instance results
         *     carry the same summary shape as `get_class_instance_summaries`.
         */
        get: operations["searchEntities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_class_instance_summaries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List instance summaries for a class
         * @description Returns one summary per instance of the given class (including
         *     instances of its subclasses, via `rdf:type/rdfs:subClassOf*`). Each
         *     summary carries the resolved preferred label (English first, then
         *     untagged, then other languages), the direct types, and a compact
         *     preview of up to three property values for display under the instance
         *     title. When `class` is omitted, summaries for all instances are
         *     returned.
         */
        get: operations["getClassInstanceSummaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_class_metadata/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get class descriptions, hierarchy links and restriction axioms
         * @description Returns metadata backing the class inspector pane: `rdfs:comment` /
         *     `skos:definition` descriptions, direct superclasses and subclasses,
         *     named equivalent classes, and the OWL restriction axioms asserted on
         *     the class (existential/universal/value restrictions and unqualified or
         *     qualified cardinality restrictions, including intersection targets
         *     expanded into their named member classes).
         */
        get: operations["getClassMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_instance_property_metadata/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an instance's direct properties with type metadata
         * @description Returns the direct outgoing statements of an instance, grouped per
         *     property and sorted, with each value tagged as an `object` reference
         *     (id plus resolved label) or a typed `literal` (JSON-native value plus
         *     XSD datatype). Property names are returned without the `has_` prefix.
         */
        get: operations["getInstancePropertyMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create_instance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an instance linked to a parent (direct SPARQL)
         * @description Creates a new UUID-named instance of class `property`, links it to the
         *     existing `parent` instance via the corresponding `has_<property>`
         *     object property, and optionally asserts initial property values from
         *     `data`. String values that match the label of an existing instance of
         *     the property's class are resolved to object references; creating
         *     nested individuals inline is rejected.
         */
        post: operations["createInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create_class_instance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a standalone labelled instance (direct SPARQL)
         * @description Creates a new UUID-named instance of the given class with an `rdfs:label`, without linking it to a parent.
         */
        post: operations["createClassInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/add_values/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add property values to an instance (direct SPARQL)
         * @description Inserts the given property values for an existing instance in a single
         *     SPARQL update transaction. List values produce one triple per element.
         *     Plain string values are kept as literals for datatype properties; for
         *     object properties they are resolved to an existing instance of the
         *     property's class by label, or a new labeled instance is created when no
         *     match exists. Explicit `instance*` references must already exist.
         */
        post: operations["addValues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/replace_values/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace property values on an instance (direct SPARQL)
         * @description Replaces the existing values of each property in `data` with the given
         *     new values in a single SPARQL update transaction. An empty list (`[]`)
         *     removes all values of that property.
         */
        post: operations["replaceValues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/replace_properties/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace an instance's property set (direct SPARQL)
         * @description Removes the instance's existing `has_*` and `rdfs:label` statements and
         *     asserts the given data instead, preserving structural metadata
         *     (`rdf:type`, `rdfs:comment`).
         */
        post: operations["replaceProperties"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/replace_value/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Atomically replace one specific property value (direct SPARQL)
         * @description Replaces one stored value with another in a single SPARQL update. The old value is matched by value equality (dangling references allowed); the new value keeps its exact datatype and language tag. When the old value no longer exists, the update is a no-op.
         */
        post: operations["replaceValue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete_value/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a single property value (direct SPARQL) */
        post: operations["deleteValue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete_values/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete all values of the given properties (direct SPARQL) */
        post: operations["deleteValues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete_instance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete an instance and all its triples (direct SPARQL)
         * @description Cascading delete: removes every outgoing (`<inst> ?p ?o`) and incoming
         *     (`?s ?p <inst>`) triple of the instance in one SPARQL update, so no
         *     orphan references remain.
         */
        post: operations["deleteInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import_coupled_kratos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a Kratos CoSimulation JSON configuration
         * @description Recursively converts a Kratos CoSimulation parameters JSON object into
         *     OWL instances (CoSim2OWL), infers class-restriction axioms for the
         *     imported structure, and persists the updated ontology to GraphDB.
         *     Runs on the in-memory Owlready2 path.
         */
        post: operations["importCoupledKratos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export_coupled_kratos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export a coupled system as Kratos CoSimulation JSON
         * @description Reconstructs the nested Kratos CoSimulation parameters JSON for a
         *     stored coupled-system instance by recursively resolving its properties.
         *     Runs on the in-memory Owlready2 path.
         */
        post: operations["exportCoupledKratos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create_coupled/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an empty coupled system
         * @description Creates a new labelled instance of the `coupled_system` class and persists the ontology. Runs on the in-memory Owlready2 path.
         */
        post: operations["createCoupled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copy_instance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy an instance with its direct properties
         * @description Creates a structural copy of an instance, optionally attaching it to a
         *     parent via the appropriate inverse property and overriding selected
         *     property values with `data`. Runs on the in-memory Owlready2 path.
         */
        post: operations["copyInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copy_instance_recursively/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy an instance and its linked sub-structure
         * @description Like `copy_instance`, but also recursively copies linked child
         *     instances down to `depth` levels (or without limit when `recursive` is
         *     `"True"`). Runs on the in-memory Owlready2 path.
         */
        post: operations["copyInstanceRecursively"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/infer_coupled_structure/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Infer class-restriction axioms for a coupled system
         * @description Runs the class-axiom inference over a coupled system's connected
         *     instances (deriving existential and cardinality restrictions from the
         *     instance structure) and persists the result. Runs on the in-memory
         *     Owlready2 path.
         */
        post: operations["inferCoupledStructure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_instance_properties_recursively/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an instance's properties as a nested structure
         * @description Returns the instance's properties with linked instances expanded
         *     in place down to `depth` levels (or without limit when `recursive` is
         *     `"True"`). Property names lose the `has_` prefix; single-valued
         *     properties are returned as scalars, multi-valued ones as arrays. Runs
         *     on the in-memory Owlready2 path.
         */
        get: operations["getInstancePropertiesRecursively"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/save_onto/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Persist the in-memory ontology to GraphDB
         * @description Pushes the current in-memory Owlready2 model to the GraphDB named graph.
         */
        post: operations["saveOnto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/save_locally/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the ontology as an OWL file (inline)
         * @description Reloads the ontology from GraphDB, serialises it to RDF/XML and returns the file.
         */
        get: operations["saveLocally"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download_owl/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the ontology as an OWL file (attachment)
         * @description Reloads the ontology from GraphDB, serialises it to RDF/XML and returns the file as a download attachment.
         */
        get: operations["downloadOwl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_class_hierarchy/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map root classes to their subclasses
         * @description Returns a mapping from each root class (no named parent) to the list of
         *     its direct subclasses. Superseded by `get_class_hierarchy_metadata` for
         *     the explorer UI.
         */
        get: operations["getClassHierarchy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_class_properties_recursively/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a class's restriction axioms as nested structures
         * @description Returns the class's restriction axioms (property, cardinality, target
         *     value) with class-valued targets expanded recursively down to `depth`
         *     levels (or without limit when `recursive` is `"True"`). Runs on the
         *     in-memory Owlready2 path.
         */
        get: operations["getClassPropertiesRecursively"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_class_instances/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List instance identifiers of a class
         * @description Returns the identifiers of all instances of the class (including subclass instances). Superseded by `get_class_instance_summaries` for the explorer UI.
         */
        get: operations["getClassInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Human-readable error message. */
            error: string;
        };
        HealthOk: {
            /** @constant */
            status: "ok";
            /** @constant */
            graphdb: "connected";
            /**
             * @description Name of the configured GraphDB repository.
             * @example coupled_modelling
             */
            repository: string;
        };
        HealthError: {
            /** @constant */
            status: "error";
            /** @constant */
            graphdb: "unavailable";
            /** @description Name of the configured GraphDB repository. */
            repository: string;
            /** @description Underlying connection error message. */
            error: string;
        };
        /**
         * @description Local identifier of an instance (UUID-based for instances created through the API).
         * @example instance_550e8400-e29b-41d4-a716-446655440000
         */
        InstanceId: string;
        /** @description A literal value (string, number or boolean). */
        ScalarValue: string | number | boolean;
        /**
         * @description Property-name to value(s) mapping. Keys are property names without the
         *     `has_` prefix (plus `label` for `rdfs:label`). Values are scalars or
         *     arrays of scalars. Whether plain strings on object properties are
         *     label-resolved to object references is documented per endpoint; the
         *     replace endpoints accept only non-string literals (numbers, booleans),
         *     `label` strings, and explicit `instance*` references.
         * @example {
         *       "echo_level": 1,
         *       "print_colors": false
         *     }
         */
        PropertyDataMap: {
            [key: string]: components["schemas"]["ScalarValue"] | components["schemas"]["ScalarValue"][];
        };
        /**
         * @description String-encoded boolean; recursion is unlimited only when the exact string `"True"` is sent.
         * @default False
         * @enum {string}
         */
        RecursiveFlag: "True" | "False";
        ClassHierarchyEntry: {
            /**
             * @description Local class name.
             * @example convergence_accelerators
             */
            class: string;
            /** @description Direct named superclasses (empty for root classes). */
            parents: string[];
        };
        PreviewItem: {
            /** @description Property name. */
            property: string;
            value: components["schemas"]["ScalarValue"];
            /**
             * @description Whether the value is a typed literal or the resolved label of a linked instance.
             * @enum {string}
             */
            kind: "literal" | "object";
        };
        SearchResults: {
            /** @description Matching classes (empty when `type=instance`). */
            classes: components["schemas"]["SearchClassResult"][];
            /** @description Matching instances (empty when `type=class`). */
            instances: components["schemas"]["InstanceSummary"][];
        };
        SearchClassResult: {
            /** @description Local class name. */
            id: string;
        };
        InstanceSummary: {
            /** @description Local instance identifier. */
            id: string;
            /** @description Preferred label (English first), falling back to the identifier. */
            label: string;
            /** @description Direct class names of the instance. */
            types: string[];
            /** @description Up to three property values for compact display (literals first). */
            property_preview: components["schemas"]["PreviewItem"][];
            /** @description True when the instance has more values than shown in the preview. */
            preview_truncated: boolean;
        };
        NamedReference: {
            /** @description Local name of the referenced entity. */
            id: string;
            /** @description Preferred label, falling back to the local name. */
            label: string;
        };
        /** @description Targets an object-property triple pointing at the referenced instance. */
        ObjectValueTarget: {
            /** @constant */
            kind: "object";
            /** @description Identifier of the linked instance the triple points at. */
            id: string;
        };
        /** @description Targets a literal triple; the datatype and language tag drive term serialization. */
        LiteralValueTarget: {
            /** @constant */
            kind: "literal";
            value: components["schemas"]["ScalarValue"];
            /**
             * @description XSD datatype IRI of the literal (defaults to plain string serialization).
             * @example http://www.w3.org/2001/XMLSchema#integer
             */
            datatype?: string;
            /**
             * @description Language tag of the literal — required to match language-tagged triples ("value"@de).
             * @example de
             */
            language?: string;
        };
        ObjectPropertyValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "object";
            /** @description Identifier of the linked instance. */
            id: string;
            /** @description Preferred label of the linked instance (falls back to the id when unlabeled). */
            label: string;
            /** @description Local class names of the linked instance. */
            types: string[];
            /** @description Up to three of the linked instance's property values, literals first. */
            property_preview: components["schemas"]["PreviewItem"][];
            /** @description Whether the linked instance has more property values than the preview shows. */
            preview_truncated: boolean;
        };
        LiteralPropertyValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "literal";
            value: components["schemas"]["ScalarValue"];
            /**
             * @description XSD datatype IRI of the literal.
             * @example http://www.w3.org/2001/XMLSchema#integer
             */
            datatype: string;
            /** @description Language tag, when present on the literal. */
            language?: string;
        };
        InstancePropertyGroup: {
            /** @description Property name without the `has_` prefix. */
            property: string;
            values: (components["schemas"]["ObjectPropertyValue"] | components["schemas"]["LiteralPropertyValue"])[];
        };
        InstanceMetadata: {
            /** @description Local instance identifier. */
            id: string;
            /** @description Preferred label, falling back to the identifier. */
            label: string;
            /** @description Project-local class names of the instance. */
            types: string[];
            /** @description Direct properties, sorted by property name. */
            properties: components["schemas"]["InstancePropertyGroup"][];
        };
        RestrictionTarget: {
            /** @description Local name of the target class, or the raw value for literal targets. */
            id: string;
            /** @description Display label ("A & B" for intersections, "Anonymous Class (id)" for unresolved blank nodes). */
            label: string;
            value?: components["schemas"]["ScalarValue"];
            /** @description XSD datatype IRI (literal targets only). */
            datatype?: string;
            /** @description Language tag (literal targets only). */
            language?: string;
            /** @description Named member classes (intersection targets only). */
            members?: components["schemas"]["NamedReference"][];
        };
        Restriction: {
            property: components["schemas"]["NamedReference"];
            /**
             * @description Type of OWL restriction.
             * @enum {string}
             */
            kind: "some_values_from" | "all_values_from" | "has_value" | "cardinality" | "min_cardinality" | "max_cardinality" | "qualified_cardinality" | "min_qualified_cardinality" | "max_qualified_cardinality";
            /** @description Cardinality bound (cardinality restrictions only). */
            cardinality?: number | string;
            /**
             * @description Nature of the restriction target.
             * @enum {string}
             */
            target_kind?: "class" | "literal" | "bnode" | "intersection" | "data_range";
            target?: components["schemas"]["RestrictionTarget"];
        };
        ClassMetadata: {
            /** @description Local class name. */
            id: string;
            /** @description Class label (currently identical to the local name). */
            label: string;
            /** @description `rdfs:comment` and `skos:definition` annotations. */
            descriptions: string[];
            superclasses: components["schemas"]["NamedReference"][];
            subclasses: components["schemas"]["NamedReference"][];
            /** @description Asserted OWL restriction axioms, sorted by property label. */
            restrictions: components["schemas"]["Restriction"][];
            equivalent_classes: components["schemas"]["NamedReference"][];
        };
        ClassAxiom: {
            /** @description Restricted property name. */
            property: string;
            /** @description Cardinality bound, when the axiom is a cardinality restriction. */
            cardinality: number | null;
            /** @description Target class name(s); nested axiom objects when expanded recursively. */
            value: string | {
                [key: string]: components["schemas"]["ClassAxiom"][];
            }[];
        };
        /**
         * @description Recursive property structure: keys are property names (without the
         *     `has_` prefix), values are scalars, arrays, or one-key objects mapping
         *     a linked instance's identifier to its own nested properties.
         * @example {
         *       "label": "FSI Mok benchmark",
         *       "problem_data": {
         *         "problem_data_1": {
         *           "parallel_type": "OpenMP",
         *           "echo_level": 1
         *         }
         *       }
         *     }
         */
        NestedProperties: {
            [key: string]: unknown;
        };
        /** @description Kratos CoSimulation parameters JSON (nested solver, coupling and data-transfer configuration). */
        KratosParameters: {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description The operation succeeded. The body is an empty JSON string. */
        EmptyCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": "";
            };
        };
        /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description GraphDB is unreachable or the repository is offline. */
        GraphDBUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        UnexpectedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: {
        InstanceDataBody: {
            content: {
                "application/json": {
                    /** @description Instance identifier. */
                    instance: string;
                    data: components["schemas"]["PropertyDataMap"];
                };
            };
        };
        CoupledSystemBody: {
            content: {
                "application/json": {
                    /** @description Identifier of the coupled-system instance. */
                    coupled_system: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOpenApiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI 3.1 specification in YAML. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GraphDB is reachable and the repository responds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOk"];
                };
            };
            /** @description Unexpected server error during the health check. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthError"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthError"];
                };
            };
        };
    };
    getClassHierarchyMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alphabetically sorted class list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassHierarchyEntry"][];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    searchEntities: {
        parameters: {
            query: {
                /**
                 * @description Search text (matched as a case-insensitive substring).
                 * @example mok
                 */
                q: string;
                /** @description Restrict results to one entity kind. */
                type?: "all" | "class" | "instance";
                /** @description Maximum results per group (1-100). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching classes and instances. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Missing or empty `q`, unknown `type`, or `limit` out of range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    getClassInstanceSummaries: {
        parameters: {
            query?: {
                /**
                 * @description Local class name to list instances for (for example `solvers`). Omit for all instances.
                 * @example solvers
                 */
                class?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance summaries sorted by label. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceSummary"][];
                };
            };
            /** @description The class does not exist in GraphDB. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    getClassMetadata: {
        parameters: {
            query: {
                /**
                 * @description Local class name (for example `coupled_system`).
                 * @example coupled_system
                 */
                class: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Class metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassMetadata"];
                };
            };
            /** @description Missing `class` parameter, or the class does not exist. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    getInstancePropertyMetadata: {
        parameters: {
            query: {
                /**
                 * @description Local instance identifier.
                 * @example instance_550e8400-e29b-41d4-a716-446655440000
                 */
                instance: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance metadata for the inspector pane. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceMetadata"];
                };
            };
            /** @description Missing `instance` parameter, or the instance does not exist. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    createInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Class name of the new instance (also selects the `has_*` linking property).
                     * @example solvers
                     */
                    property: string;
                    /** @description Identifier of the existing parent instance. */
                    parent: string;
                    data?: components["schemas"]["PropertyDataMap"];
                };
            };
        };
        responses: {
            /** @description Identifier of the created instance. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceId"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    createClassInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Class to instantiate.
                     * @example solvers
                     */
                    class: string;
                    /**
                     * @description Human-readable label stored as `rdfs:label`.
                     * @example Airfoil fluid solver
                     */
                    label: string;
                };
            };
        };
        responses: {
            /** @description Identifier of the created instance. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceId"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    addValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["InstanceDataBody"];
        responses: {
            201: components["responses"]["EmptyCreated"];
            400: components["responses"]["BadRequest"];
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    replaceValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["InstanceDataBody"];
        responses: {
            201: components["responses"]["EmptyCreated"];
            400: components["responses"]["BadRequest"];
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    replaceProperties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["InstanceDataBody"];
        responses: {
            201: components["responses"]["EmptyCreated"];
            400: components["responses"]["BadRequest"];
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    replaceValue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Instance identifier. */
                    instance: string;
                    /** @description Property name (without the `has_` prefix). */
                    property: string;
                    /** @description The currently stored value to replace. */
                    old_value: components["schemas"]["ObjectValueTarget"] | components["schemas"]["LiteralValueTarget"];
                    /** @description The replacement value. */
                    new_value: components["schemas"]["ObjectValueTarget"] | components["schemas"]["LiteralValueTarget"];
                };
            };
        };
        responses: {
            201: components["responses"]["EmptyCreated"];
            400: components["responses"]["BadRequest"];
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    deleteValue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Instance identifier. */
                    instance: string;
                    /**
                     * @description Property name (without the `has_` prefix).
                     * @example parallel_type
                     */
                    property: string;
                    /** @description The value to delete. The typed forms delete the exact triple (correct datatype serialization); a bare scalar is matched by serialization guess. */
                    value: components["schemas"]["ObjectValueTarget"] | components["schemas"]["LiteralValueTarget"] | components["schemas"]["ScalarValue"];
                };
            };
        };
        responses: {
            201: components["responses"]["EmptyCreated"];
            400: components["responses"]["BadRequest"];
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    deleteValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Instance identifier. */
                    instance: string;
                    /**
                     * @description Property names whose values are removed (without the `has_` prefix).
                     * @example [
                     *       "echo_level",
                     *       "parallel_type"
                     *     ]
                     */
                    properties: string[];
                };
            };
        };
        responses: {
            201: components["responses"]["EmptyCreated"];
            400: components["responses"]["BadRequest"];
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    deleteInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Identifier of the instance to delete. */
                    instance: string;
                };
            };
        };
        responses: {
            /** @description The instance was deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "success";
                        /** @description Identifier of the deleted instance. */
                        instance: string;
                    };
                };
            };
            /** @description Missing `instance` parameter, or the instance does not exist. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["UnexpectedError"];
            503: components["responses"]["GraphDBUnavailable"];
        };
    };
    importCoupledKratos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    data: components["schemas"]["KratosParameters"];
                    /**
                     * @description Label for the imported coupled system.
                     * @example FSI Mok benchmark
                     */
                    label: string;
                };
            };
        };
        responses: {
            /** @description Identifier of the created coupled-system instance. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceId"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    exportCoupledKratos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CoupledSystemBody"];
        responses: {
            /** @description The reconstructed Kratos parameters object. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KratosParameters"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createCoupled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Label for the new coupled system. */
                    label: string;
                };
            };
        };
        responses: {
            /** @description Identifier of the created coupled-system instance. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceId"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    copyInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Identifier of the instance to copy. */
                    instance: string;
                    /** @description Optional parent instance to attach the copy to. */
                    parent?: string;
                    data?: components["schemas"]["PropertyDataMap"];
                };
            };
        };
        responses: {
            /** @description Identifier of the created copy. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceId"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    copyInstanceRecursively: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Identifier of the instance to copy. */
                    instance: string;
                    /** @description Optional parent instance to attach the copy to. */
                    parent?: string;
                    data?: components["schemas"]["PropertyDataMap"];
                    /**
                     * @description Recursion depth (levels of linked instances to copy).
                     * @default 1
                     */
                    depth?: number | string;
                    recursive?: components["schemas"]["RecursiveFlag"];
                };
            };
        };
        responses: {
            /** @description Identifier of the created copy. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceId"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    inferCoupledStructure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CoupledSystemBody"];
        responses: {
            201: components["responses"]["EmptyCreated"];
            400: components["responses"]["BadRequest"];
        };
    };
    getInstancePropertiesRecursively: {
        parameters: {
            query: {
                /** @description Instance identifier. */
                instance: string;
                /** @description Recursion depth. */
                depth?: number;
                /** @description Unlimited recursion when `"True"`. */
                recursive?: components["schemas"]["RecursiveFlag"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nested property structure. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NestedProperties"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    saveOnto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["EmptyCreated"];
            400: components["responses"]["BadRequest"];
        };
    };
    saveLocally: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ontology file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/rdf+xml": string;
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    downloadOwl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ontology file as an attachment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/rdf+xml": string;
                };
            };
            500: components["responses"]["UnexpectedError"];
        };
    };
    getClassHierarchy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Root-class to subclasses mapping. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "coupled_system": [],
                     *       "settings": [
                     *         "io_settings_1",
                     *         "solver_settings_1"
                     *       ]
                     *     }
                     */
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getClassPropertiesRecursively: {
        parameters: {
            query: {
                /** @description Class name. */
                class: string;
                /** @description Recursion depth. */
                depth?: number;
                /** @description Unlimited recursion when `"True"`. */
                recursive?: components["schemas"]["RecursiveFlag"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of class axioms. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassAxiom"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getClassInstances: {
        parameters: {
            query: {
                /** @description Class name. */
                class: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance identifiers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
