/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1.0/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download this OpenAPI specification
         * @description Serves the OpenAPI document generated from the running backend, so clients and tooling can generate typed bindings without a copy of the repository.
         */
        get: operations["getOpenApiSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check GraphDB connectivity
         * @description Verifies that the configured GraphDB repository answers a trivial `ASK` query.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/get_class_hierarchy_metadata/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all ontology classes with their direct parents
         * @description Returns every project-local OWL class together with the list of its direct named superclasses.
         *     The frontend builds the class tree from the parent arrays (classes with an empty `parents` array are roots).
         */
        get: operations["getClassHierarchyMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search classes and instances by name or label
         * @description Case-insensitive substring search over the local names and labels of project classes and instances.
         *     Each result group is capped at `limit`; matches on a name prefix rank before other matches.
         *     Instance results carry the same summary shape as `get_class_instance_summaries`.
         */
        get: operations["searchEntities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/get_class_instance_summaries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List instance summaries for a class
         * @description Returns one summary per instance of the given class (including instances of its subclasses, via
         *     `rdf:type/rdfs:subClassOf*`). Each summary carries the resolved preferred label (English first, then
         *     untagged, then other languages), the direct types, and a compact preview of up to three property
         *     values for display under the instance title. When `class` is omitted, summaries for all instances are returned.
         */
        get: operations["getClassInstanceSummaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/get_class_metadata/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get class descriptions, hierarchy links and restriction axioms
         * @description Returns metadata backing the class inspector pane: `rdfs:comment` / `skos:definition` descriptions,
         *     direct superclasses and subclasses, named equivalent classes, and the OWL restriction axioms asserted on
         *     the class (existential/universal/value restrictions and unqualified or qualified cardinality restrictions,
         *     including intersection targets expanded into their named member classes).
         */
        get: operations["getClassMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/get_instance_property_metadata/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an instance's direct properties with type metadata
         * @description Returns the direct outgoing statements of an instance, grouped per property and sorted, with each value
         *     tagged as an `object` reference (id plus resolved label) or a typed `literal` (JSON-native value plus XSD
         *     datatype). Property names are returned without the `has_` prefix.
         */
        get: operations["getInstancePropertyMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/get_value_deletion_preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview what removing an object link would delete
         * @description Read-only counterpart of `delete_value` for an object link: whether the linked instance would be deleted
         *     with its owned subtree (nothing else reaches it afterwards) or kept.
         */
        get: operations["getValueDeletionPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/get_instance_deletion_preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview what a cascading deletion of an instance would remove
         * @description Read-only counterpart of `delete_instance`: the instances that would be deleted (the requested one first),
         *     the reachable ones that would be kept, and the surviving instances whose link would be removed.
         */
        get: operations["getInstanceDeletionPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/create_instance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an instance linked to a parent (direct SPARQL)
         * @description Creates a new UUID-named instance of class `property`, links it to the existing `parent` instance via the
         *     corresponding `has_<property>` object property, and optionally asserts initial property values from `data`.
         *     String values that match the label of an existing instance of the property's class are resolved to object
         *     references; creating nested individuals inline is rejected.
         */
        post: operations["createInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/create_class_instance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a standalone labelled instance (direct SPARQL)
         * @description Creates a new UUID-named instance of the given class with an `rdfs:label`, without linking it to a parent.
         */
        post: operations["createClassInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/add_values/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add property values to an instance (direct SPARQL)
         * @description Inserts the given property values for an existing instance in a single SPARQL update transaction. List
         *     values produce one triple per element. Plain string values are kept as literals for datatype properties; for
         *     object properties they are resolved to an existing instance of the property's class by label, or a new labeled
         *     instance is created when no match exists. Explicit `instance*` references must already exist.
         */
        post: operations["addValues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/replace_values/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace property values on an instance (direct SPARQL)
         * @description Replaces the existing values of each property in `data` with the given new values in a single SPARQL update
         *     transaction. An empty list (`[]`) removes all values of that property.
         */
        post: operations["replaceValues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/replace_properties/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace an instance's property set (direct SPARQL)
         * @description Removes the instance's existing `has_*` and `rdfs:label` statements and asserts the given data instead,
         *     preserving structural metadata (`rdf:type`, `rdfs:comment`).
         */
        post: operations["replaceProperties"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/replace_value/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Atomically replace one specific property value (direct SPARQL)
         * @description Replaces one stored value with another in a single SPARQL update. The old value is matched by value equality
         *     (dangling references allowed); the new value keeps its exact datatype and language tag. When the old value no
         *     longer exists, the update is a no-op. Replacing an object value removes the old link only; the previous target
         *     is not garbage-collected.
         */
        post: operations["replaceValue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/delete_value/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a single property value (direct SPARQL)
         * @description Removes the triple. When the value is an object link and `cascade` is set (the default), the linked instance's
         *     owned subtree is deleted as well if nothing else reaches it afterwards: the same ownership rule as
         *     `delete_instance`. A coupled system, a target still linked from elsewhere, a link that is not stored, and the
         *     instance holding the link are never collected. The removal and the collection run in one transactional update.
         *     Use `get_value_deletion_preview` to see the outcome first.
         */
        post: operations["deleteValue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/delete_values/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete all values of the given properties (direct SPARQL)
         * @description Removes the triples only; unlinked instances are not garbage-collected.
         */
        post: operations["deleteValues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/delete_instance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete an instance and, by default, its owned subtree (direct SPARQL)
         * @description Removes every outgoing and incoming triple of the instance in one transactional SPARQL update. With `cascade`
         *     (the default) the instance's owned subtree goes with it: every individual reachable through `has_*` links that
         *     is not reachable from outside the subtree. Coupled systems are never owned by another instance, so traversal
         *     stops at them. Individuals still reachable from elsewhere (an instance linked from outside and everything below
         *     it, shared vocabulary terms for example) are kept and reported in `kept`. With `cascade: false` only the instance
         *     itself is removed and its children are left in place. Use `get_instance_deletion_preview` to see the sets before
         *     deleting.
         */
        post: operations["deleteInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/import_coupled_kratos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a Kratos CoSimulation JSON configuration
         * @description Recursively converts a Kratos CoSimulation parameters JSON object into OWL instances (CoSim2OWL), infers
         *     class-restriction axioms for the imported structure, and persists the updated ontology to GraphDB. Runs on
         *     the in-memory Owlready2 path.
         */
        post: operations["importCoupledKratos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/export_coupled_kratos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export a coupled system as Kratos CoSimulation JSON
         * @description Reconstructs the nested Kratos CoSimulation parameters JSON for a stored coupled-system instance by
         *     recursively resolving its properties. Runs on the in-memory Owlready2 path.
         */
        post: operations["exportCoupledKratos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/create_coupled/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an empty coupled system
         * @description Creates a new labelled instance of the `coupled_system` class and persists the ontology. Runs on the
         *     in-memory Owlready2 path.
         */
        post: operations["createCoupled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/copy_instance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy an instance with its direct properties
         * @description Creates a structural copy of an instance, optionally attaching it to a parent via the appropriate inverse
         *     property and overriding selected property values with `data`. Runs on the in-memory Owlready2 path.
         */
        post: operations["copyInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/copy_instance_recursively/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy an instance and its linked sub-structure
         * @description Like `copy_instance`, but also recursively copies linked child instances down to `depth` levels (or without
         *     limit when `recursive` is true). Runs on the in-memory Owlready2 path.
         */
        post: operations["copyInstanceRecursively"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/infer_coupled_structure/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Infer class-restriction axioms for a coupled system
         * @description Runs the class-axiom inference over a coupled system's connected instances (deriving existential and
         *     cardinality restrictions from the instance structure) and persists the result. Runs on the in-memory
         *     Owlready2 path.
         */
        post: operations["inferCoupledStructure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/get_instance_properties_recursively/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an instance's properties as a nested structure
         * @description Returns the instance's properties with linked instances expanded in place down to `depth` levels (or
         *     without limit when `recursive` is true). Property names lose the `has_` prefix; single-valued properties are
         *     returned as scalars, multi-valued ones as arrays. Runs on the in-memory Owlready2 path.
         */
        get: operations["getInstancePropertiesRecursively"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/save_onto/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Persist the in-memory ontology to GraphDB
         * @description Pushes the current in-memory Owlready2 model to the GraphDB named graph.
         */
        post: operations["saveOnto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/save_locally/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the ontology as an OWL file (inline)
         * @description Reloads the ontology from GraphDB, serialises it to RDF/XML and returns the file.
         */
        get: operations["saveLocally"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/download_owl/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the ontology as an OWL file (attachment)
         * @description Reloads the ontology from GraphDB, serialises it to RDF/XML and returns the file as a download attachment.
         */
        get: operations["downloadOwl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/get_class_hierarchy/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map root classes to their subclasses
         * @description Returns a mapping from each root class (no named parent) to the list of its direct subclasses. Superseded by
         *     `get_class_hierarchy_metadata` for the explorer UI.
         */
        get: operations["getClassHierarchy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/get_class_properties_recursively/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a class's restriction axioms as nested structures
         * @description Returns the class's restriction axioms (property, cardinality, target value) with class-valued targets
         *     expanded recursively down to `depth` levels (or without limit when `recursive` is true). Runs on the in-memory
         *     Owlready2 path.
         */
        get: operations["getClassPropertiesRecursively"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/get_class_instances/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List instance identifiers of a class
         * @description Returns the identifiers of all instances of the class (including subclass instances). Superseded by
         *     `get_class_instance_summaries` for the explorer UI.
         */
        get: operations["getClassInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClassAxiom */
        ClassAxiom: {
            /**
             * Property
             * @description Restricted property name.
             */
            property: string;
            /**
             * Cardinality
             * @description Cardinality bound, when the axiom is a cardinality restriction.
             */
            cardinality: number | null;
            /**
             * Value
             * @description Target class name, the member class names of an intersection target, or one-key objects mapping a member class to its own axioms when expanded recursively.
             */
            value: string | (string | {
                [key: string]: unknown;
            })[];
        };
        /** ClassHierarchyEntry */
        ClassHierarchyEntry: {
            /**
             * Class
             * @description Local class name.
             * @example convergence_accelerators
             */
            class: string;
            /**
             * Parents
             * @description Direct named superclasses (empty for root classes).
             */
            parents: string[];
        };
        /** ClassMetadata */
        ClassMetadata: {
            /**
             * Id
             * @description Local class name.
             */
            id: string;
            /**
             * Label
             * @description Class label (currently identical to the local name).
             */
            label: string;
            /**
             * Descriptions
             * @description `rdfs:comment` and `skos:definition` annotations.
             */
            descriptions: string[];
            /** Superclasses */
            superclasses: components["schemas"]["NamedReference"][];
            /** Subclasses */
            subclasses: components["schemas"]["NamedReference"][];
            /**
             * Restrictions
             * @description Asserted OWL restriction axioms, sorted by property label.
             */
            restrictions: components["schemas"]["Restriction"][];
            /** Equivalent Classes */
            equivalent_classes: components["schemas"]["NamedReference"][];
        };
        /** CopyInstanceBody */
        CopyInstanceBody: {
            /**
             * Instance
             * @description Identifier of the instance to copy.
             */
            instance: string;
            /**
             * Parent
             * @description Optional parent instance to attach the copy to.
             */
            parent?: string;
            /** Data */
            data?: components["schemas"]["PropertyDataMap"];
        };
        /** CopyInstanceRecursivelyBody */
        CopyInstanceRecursivelyBody: {
            /**
             * Instance
             * @description Identifier of the instance to copy.
             */
            instance: string;
            /**
             * Parent
             * @description Optional parent instance to attach the copy to.
             */
            parent?: string;
            /** Data */
            data?: components["schemas"]["PropertyDataMap"];
            /**
             * Depth
             * @description Recursion depth (levels of linked instances to copy); null for no limit.
             * @default 1
             */
            depth: number | null;
            /**
             * Recursive
             * @description Unlimited recursion when true.
             * @default false
             */
            recursive: boolean;
        };
        /** CoupledSystemBody */
        CoupledSystemBody: {
            /**
             * Coupled System
             * @description Identifier of the coupled-system instance.
             */
            coupled_system: string;
        };
        /** CreateClassInstanceBody */
        CreateClassInstanceBody: {
            /**
             * Class
             * @description Class to instantiate.
             * @example solvers
             */
            class: string;
            /**
             * Label
             * @description Human-readable label stored as `rdfs:label`.
             * @example Airfoil fluid solver
             */
            label: string;
        };
        /** CreateCoupledBody */
        CreateCoupledBody: {
            /**
             * Label
             * @description Label for the new coupled system.
             */
            label: string;
        };
        /** CreateInstanceBody */
        CreateInstanceBody: {
            /**
             * Property
             * @description Class name of the new instance (also selects the `has_*` linking property).
             * @example solvers
             */
            property: string;
            /**
             * Parent
             * @description Identifier of the existing parent instance.
             */
            parent: string;
            /** Data */
            data?: components["schemas"]["PropertyDataMap"];
        };
        /** DeleteInstanceBody */
        DeleteInstanceBody: {
            /**
             * Instance
             * @description Identifier of the instance to delete.
             */
            instance: string;
            /**
             * Cascade
             * @description Also delete the instance's owned subtree.
             * @default true
             */
            cascade: boolean;
        };
        /** DeleteValueBody */
        DeleteValueBody: {
            /**
             * Instance
             * @description Instance identifier.
             */
            instance: string;
            /**
             * Property
             * @description Property name (without the `has_` prefix).
             * @example parallel_type
             */
            property: string;
            /**
             * Value
             * @description The value to delete. The typed forms delete the exact triple (correct datatype serialization); a bare scalar is matched by serialization guess.
             */
            value: (components["schemas"]["ObjectValueTarget"] | components["schemas"]["LiteralValueTarget"]) | components["schemas"]["ScalarValue"];
            /**
             * Cascade
             * @description Also delete the unlinked instance's owned subtree when nothing else reaches it.
             * @default true
             */
            cascade: boolean;
        };
        /** DeleteValuesBody */
        DeleteValuesBody: {
            /**
             * Instance
             * @description Instance identifier.
             */
            instance: string;
            /**
             * Properties
             * @description Property names whose values are removed (without the `has_` prefix).
             * @example [
             *       "echo_level",
             *       "parallel_type"
             *     ]
             */
            properties: string[];
        };
        /** DeletionPreview */
        DeletionPreview: {
            /**
             * Deleted
             * @description Identifiers the deletion removes, the root of the collected subtree first; empty when nothing is collected.
             */
            deleted: string[];
            /**
             * Kept
             * @description Reachable instances kept because they are still reachable from outside the collected subtree (an instance linked from elsewhere, or a coupled system, plus everything below it).
             */
            kept: string[];
            /**
             * Instance
             * @description Identifier of the instance the deletion applies to.
             */
            instance: string;
            /**
             * Unlinked From
             * @description Surviving instances whose link to the deleted instance is removed.
             */
            unlinked_from: string[];
        };
        /**
         * @description The operation succeeded. The body is an empty JSON string.
         * @constant
         */
        EmptyBody: "";
        /** Error */
        Error: {
            /**
             * Error
             * @description Human-readable error message.
             */
            error: string;
        };
        /** HealthError */
        HealthError: {
            /**
             * Status
             * @constant
             */
            status: "error";
            /**
             * Graphdb
             * @constant
             */
            graphdb: "unavailable";
            /**
             * Repository
             * @description Name of the configured GraphDB repository.
             */
            repository: string;
            /**
             * Error
             * @description Underlying connection error message.
             */
            error: string;
        };
        /** HealthOk */
        HealthOk: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Graphdb
             * @constant
             */
            graphdb: "connected";
            /**
             * Repository
             * @description Name of the configured GraphDB repository.
             * @example coupled_modelling
             */
            repository: string;
        };
        /** ImportKratosBody */
        ImportKratosBody: {
            data: components["schemas"]["KratosParameters"];
            /**
             * Label
             * @description Label for the imported coupled system.
             * @example FSI Mok benchmark
             */
            label: string;
        };
        /** InstanceDataBody */
        InstanceDataBody: {
            /**
             * Instance
             * @description Instance identifier.
             */
            instance: string;
            data: components["schemas"]["PropertyDataMap"];
        };
        /** InstanceDeletionResult */
        InstanceDeletionResult: {
            /**
             * Deleted
             * @description Identifiers the deletion removes, the root of the collected subtree first; empty when nothing is collected.
             */
            deleted: string[];
            /**
             * Kept
             * @description Reachable instances kept because they are still reachable from outside the collected subtree (an instance linked from elsewhere, or a coupled system, plus everything below it).
             */
            kept: string[];
            /**
             * Instance
             * @description Identifier of the instance the deletion applies to.
             */
            instance: string;
            /**
             * Unlinked From
             * @description Surviving instances whose link to the deleted instance is removed.
             */
            unlinked_from: string[];
            /**
             * Status
             * @constant
             */
            status: "success";
        };
        /**
         * @description Local identifier of an instance (UUID-based for instances created through the API).
         * @example instance_550e8400-e29b-41d4-a716-446655440000
         */
        InstanceId: string;
        /** InstanceMetadata */
        InstanceMetadata: {
            /**
             * Id
             * @description Local instance identifier.
             */
            id: string;
            /**
             * Label
             * @description Preferred label, falling back to the identifier.
             */
            label: string;
            /**
             * Types
             * @description Project-local class names of the instance.
             */
            types: string[];
            /**
             * Properties
             * @description Direct properties, sorted by property name.
             */
            properties: components["schemas"]["InstancePropertyGroup"][];
        };
        /** InstancePropertyGroup */
        InstancePropertyGroup: {
            /**
             * Property
             * @description Property name without the `has_` prefix.
             */
            property: string;
            /** Values */
            values: (components["schemas"]["ObjectPropertyValue"] | components["schemas"]["LiteralPropertyValue"])[];
        };
        /** InstanceSummary */
        InstanceSummary: {
            /**
             * Id
             * @description Local instance identifier.
             */
            id: string;
            /**
             * Label
             * @description Preferred label (English first), falling back to the identifier.
             */
            label: string;
            /**
             * Types
             * @description Direct class names of the instance.
             */
            types: string[];
            /**
             * Property Preview
             * @description Up to three property values for compact display (literals first).
             */
            property_preview: components["schemas"]["PreviewItem"][];
            /**
             * Preview Truncated
             * @description True when the instance has more values than shown in the preview.
             */
            preview_truncated: boolean;
        };
        /** @description Kratos CoSimulation parameters JSON (nested solver, coupling and data-transfer configuration). */
        KratosParameters: {
            [key: string]: unknown;
        };
        /** LiteralPropertyValue */
        LiteralPropertyValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "literal";
            value: components["schemas"]["ScalarValue"];
            /**
             * Datatype
             * @description XSD datatype IRI of the literal.
             * @example http://www.w3.org/2001/XMLSchema#integer
             */
            datatype: string;
            /**
             * Language
             * @description Language tag, when present on the literal.
             */
            language?: string;
        };
        /**
         * LiteralValueTarget
         * @description Targets a literal triple; the datatype and language tag drive term serialization.
         */
        LiteralValueTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "literal";
            value: components["schemas"]["ScalarValue"];
            /**
             * Datatype
             * @description XSD datatype IRI of the literal (defaults to plain string serialization).
             * @example http://www.w3.org/2001/XMLSchema#integer
             */
            datatype?: string;
            /**
             * Language
             * @description Language tag of the literal, required to match language-tagged triples ("value"@de).
             * @example de
             */
            language?: string;
        };
        /** NamedReference */
        NamedReference: {
            /**
             * Id
             * @description Local name of the referenced entity.
             */
            id: string;
            /**
             * Label
             * @description Preferred label, falling back to the local name.
             */
            label: string;
        };
        /**
         * @description Recursive property structure: keys are property names (without the `has_` prefix), values are scalars, arrays, or one-key objects mapping a linked instance's identifier to its own nested properties.
         * @example {
         *       "label": "FSI Mok benchmark",
         *       "problem_data": {
         *         "problem_data_1": {
         *           "echo_level": 1,
         *           "parallel_type": "OpenMP"
         *         }
         *       }
         *     }
         */
        NestedProperties: {
            [key: string]: unknown;
        };
        /**
         * ObjectPropertyValue
         * @description A linked instance: the summary shape plus the value kind.
         */
        ObjectPropertyValue: {
            /**
             * Id
             * @description Local instance identifier.
             */
            id: string;
            /**
             * Label
             * @description Preferred label (English first), falling back to the identifier.
             */
            label: string;
            /**
             * Types
             * @description Direct class names of the instance.
             */
            types: string[];
            /**
             * Property Preview
             * @description Up to three property values for compact display (literals first).
             */
            property_preview: components["schemas"]["PreviewItem"][];
            /**
             * Preview Truncated
             * @description True when the instance has more values than shown in the preview.
             */
            preview_truncated: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "object";
        };
        /**
         * ObjectValueTarget
         * @description Targets an object-property triple pointing at the referenced instance.
         */
        ObjectValueTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "object";
            /**
             * Id
             * @description Identifier of the linked instance the triple points at.
             */
            id: string;
        };
        /** PreviewItem */
        PreviewItem: {
            /**
             * Property
             * @description Property name.
             */
            property: string;
            value: components["schemas"]["ScalarValue"];
            /**
             * Kind
             * @description Whether the value is a typed literal or the resolved label of a linked instance.
             * @enum {string}
             */
            kind: "literal" | "object";
        };
        /**
         * @description Property-name to value(s) mapping. Keys are property names without the `has_` prefix (plus `label` for `rdfs:label`). Values are scalars or arrays of scalars. Whether plain strings on object properties are label-resolved to object references is documented per endpoint; the replace endpoints accept only non-string literals (numbers, booleans), `label` strings, and explicit `instance*` references.
         * @example {
         *       "echo_level": 1,
         *       "print_colors": false
         *     }
         */
        PropertyDataMap: {
            [key: string]: components["schemas"]["ScalarValue"] | components["schemas"]["ScalarValue"][];
        };
        /** ReplaceValueBody */
        ReplaceValueBody: {
            /**
             * Instance
             * @description Instance identifier.
             */
            instance: string;
            /**
             * Property
             * @description Property name (without the `has_` prefix).
             */
            property: string;
            /**
             * Old Value
             * @description The currently stored value to replace.
             */
            old_value: components["schemas"]["ObjectValueTarget"] | components["schemas"]["LiteralValueTarget"];
            /**
             * New Value
             * @description The replacement value.
             */
            new_value: components["schemas"]["ObjectValueTarget"] | components["schemas"]["LiteralValueTarget"];
        };
        /** Restriction */
        Restriction: {
            property: components["schemas"]["NamedReference"];
            /**
             * Kind
             * @description Type of OWL restriction.
             * @enum {string}
             */
            kind: "some_values_from" | "all_values_from" | "has_value" | "cardinality" | "min_cardinality" | "max_cardinality" | "qualified_cardinality" | "min_qualified_cardinality" | "max_qualified_cardinality";
            /**
             * Cardinality
             * @description Cardinality bound (cardinality restrictions only).
             */
            cardinality?: number | string;
            /**
             * Target Kind
             * @description Nature of the restriction target.
             * @enum {string}
             */
            target_kind?: "class" | "literal" | "bnode" | "intersection" | "data_range";
            target?: components["schemas"]["RestrictionTarget"];
        };
        /** RestrictionTarget */
        RestrictionTarget: {
            /**
             * Id
             * @description Local name of the target class, or the raw value for literal targets.
             */
            id: string;
            /**
             * Label
             * @description Display label ("A & B" for intersections, "Anonymous Class (id)" for unresolved blank nodes).
             */
            label: string;
            value?: components["schemas"]["ScalarValue"];
            /**
             * Datatype
             * @description XSD datatype IRI (literal targets only).
             */
            datatype?: string;
            /**
             * Language
             * @description Language tag (literal targets only).
             */
            language?: string;
            /**
             * Members
             * @description Named member classes (intersection targets only).
             */
            members?: components["schemas"]["NamedReference"][];
        };
        /** @description A literal value (string, number or boolean). */
        ScalarValue: string | number | boolean;
        /** SearchClassResult */
        SearchClassResult: {
            /**
             * Id
             * @description Local class name.
             */
            id: string;
        };
        /** SearchResults */
        SearchResults: {
            /**
             * Classes
             * @description Matching classes (empty when `type=instance`).
             */
            classes: components["schemas"]["SearchClassResult"][];
            /**
             * Instances
             * @description Matching instances (empty when `type=class`).
             */
            instances: components["schemas"]["InstanceSummary"][];
        };
        /** UnlinkResult */
        UnlinkResult: {
            /**
             * Deleted
             * @description Identifiers the deletion removes, the root of the collected subtree first; empty when nothing is collected.
             */
            deleted: string[];
            /**
             * Kept
             * @description Reachable instances kept because they are still reachable from outside the collected subtree (an instance linked from elsewhere, or a coupled system, plus everything below it).
             */
            kept: string[];
            /**
             * Target
             * @description The unlinked instance, or null when the value was a literal. It appears in `deleted` when collected, in `kept` when it survives (still linked from elsewhere, a coupled system, the link holder itself, `cascade` off, or the link was not stored), and in neither when it is not an individual (a dangling reference or a class). The instance holding the link is never collected; it is listed in `kept` when the target is collected and a link below the target leads back to it.
             */
            target: string | null;
        };
        /** ValueDeletionResult */
        ValueDeletionResult: {
            /**
             * Deleted
             * @description Identifiers the deletion removes, the root of the collected subtree first; empty when nothing is collected.
             */
            deleted: string[];
            /**
             * Kept
             * @description Reachable instances kept because they are still reachable from outside the collected subtree (an instance linked from elsewhere, or a coupled system, plus everything below it).
             */
            kept: string[];
            /**
             * Target
             * @description The unlinked instance, or null when the value was a literal. It appears in `deleted` when collected, in `kept` when it survives (still linked from elsewhere, a coupled system, the link holder itself, `cascade` off, or the link was not stored), and in neither when it is not an individual (a dangling reference or a class). The instance holding the link is never collected; it is listed in `kept` when the target is collected and a link below the target leads back to it.
             */
            target: string | null;
            /**
             * Status
             * @constant
             */
            status: "success";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOpenApiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI 3.1 specification in YAML. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GraphDB is reachable and the repository responds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOk"];
                };
            };
            /** @description Unexpected server error during the health check. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthError"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthError"];
                };
            };
        };
    };
    getClassHierarchyMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alphabetically sorted class list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassHierarchyEntry"][];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    searchEntities: {
        parameters: {
            query: {
                /** @description Search text (matched as a case-insensitive substring). */
                q: string;
                /** @description Restrict results to one entity kind. */
                type?: "all" | "class" | "instance";
                /** @description Maximum results per group (1-100). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching classes and instances. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Missing or empty `q`, unknown `type`, or `limit` out of range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getClassInstanceSummaries: {
        parameters: {
            query?: {
                /** @description Local class name to list instances for (for example `solvers`). Omit for all instances. */
                class?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance summaries sorted by label. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceSummary"][];
                };
            };
            /** @description The class does not exist in GraphDB. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getClassMetadata: {
        parameters: {
            query: {
                /** @description Local class name (for example `coupled_system`). */
                class: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Class metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassMetadata"];
                };
            };
            /** @description Missing `class` parameter, or the class does not exist. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getInstancePropertyMetadata: {
        parameters: {
            query: {
                /** @description Local instance identifier. */
                instance: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance metadata for the inspector pane. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceMetadata"];
                };
            };
            /** @description Missing `instance` parameter, or the identifier is not an existing individual (classes and properties do not count). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getValueDeletionPreview: {
        parameters: {
            query: {
                /** @description Identifier of the instance holding the link. */
                instance: string;
                /** @description Property name (without the `has_` prefix). */
                property: string;
                /** @description Identifier of the linked instance. */
                target: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The unlink preview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnlinkResult"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getInstanceDeletionPreview: {
        parameters: {
            query: {
                /** @description Local instance identifier. */
                instance: string;
                /** @description Preview the cascading (default) or the single-instance deletion. */
                cascade?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deletion preview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionPreview"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInstanceBody"];
            };
        };
        responses: {
            /** @description Identifier of the created instance. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceId"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createClassInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClassInstanceBody"];
            };
        };
        responses: {
            /** @description Identifier of the created instance. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceId"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceDataBody"];
            };
        };
        responses: {
            /** @description The operation succeeded. The body is an empty JSON string. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyBody"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    replaceValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceDataBody"];
            };
        };
        responses: {
            /** @description The operation succeeded. The body is an empty JSON string. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyBody"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    replaceProperties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceDataBody"];
            };
        };
        responses: {
            /** @description The operation succeeded. The body is an empty JSON string. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyBody"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    replaceValue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceValueBody"];
            };
        };
        responses: {
            /** @description The operation succeeded. The body is an empty JSON string. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyBody"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteValue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteValueBody"];
            };
        };
        responses: {
            /** @description The value was deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValueDeletionResult"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteValuesBody"];
            };
        };
        responses: {
            /** @description The operation succeeded. The body is an empty JSON string. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyBody"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteInstanceBody"];
            };
        };
        responses: {
            /** @description The instance was deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDeletionResult"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description GraphDB is unreachable or the repository is offline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    importCoupledKratos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportKratosBody"];
            };
        };
        responses: {
            /** @description Identifier of the created coupled-system instance. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceId"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    exportCoupledKratos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoupledSystemBody"];
            };
        };
        responses: {
            /** @description The reconstructed Kratos parameters object. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KratosParameters"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createCoupled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCoupledBody"];
            };
        };
        responses: {
            /** @description Identifier of the created coupled-system instance. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceId"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    copyInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyInstanceBody"];
            };
        };
        responses: {
            /** @description Identifier of the created copy. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceId"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    copyInstanceRecursively: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyInstanceRecursivelyBody"];
            };
        };
        responses: {
            /** @description Identifier of the created copy. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceId"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    inferCoupledStructure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoupledSystemBody"];
            };
        };
        responses: {
            /** @description The operation succeeded. The body is an empty JSON string. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyBody"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getInstancePropertiesRecursively: {
        parameters: {
            query: {
                /** @description Instance identifier. */
                instance: string;
                /** @description Recursion depth. */
                depth?: number;
                /** @description Unlimited recursion when true. */
                recursive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nested property structure. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NestedProperties"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    saveOnto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The operation succeeded. The body is an empty JSON string. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyBody"];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    saveLocally: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ontology file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/rdf+xml": string;
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    downloadOwl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ontology file as an attachment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/rdf+xml": string;
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getClassHierarchy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Root-class to subclasses mapping. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getClassPropertiesRecursively: {
        parameters: {
            query: {
                /** @description Class name. */
                class: string;
                /** @description Recursion depth. */
                depth?: number;
                /** @description Unlimited recursion when true. */
                recursive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of class axioms. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassAxiom"][];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getClassInstances: {
        parameters: {
            query: {
                /** @description Class name. */
                class: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance identifiers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Invalid input (missing parameters, unknown subject/class, or validation failure). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
